---
title: "Pre-course work - Open Science Tools HS23"
editor: source
execute: 
  echo: false
  warning: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

Thank you for your interest in this course. Your course instructor [Lars Schöbitz](https://ghe.ethz.ch/about/people/person-detail.MjkyODc2.TGlzdC80MTI2LC0xNDYwMDMwNTU3.html) is looking forward to meet you. We will meet in Room HG F 33.5 at the following times:

-   **Day 1:** 17th October 2023 - 08:30 am to 12:30 pm CET
-   **Day 2:** 24th October 2023 - 08:30 am to 12:30 pm CET

Please ensure you bring the following items to class:

-   a laptop, connected to ETH wifi
-   a browser installation on your laptop

Prior to Day 1, there is some pre-work for you to do. This pre-work will ensure that we can focus our time together on learning instead of setting up infrastructure.

## {{< fa circle-question >}} What do I need to prepare?

Prior to Day 1, please complete the following **X** steps:

-   [Step 1](01-github.html): Get an account on GitHub and setup a GitHub Personal Access Token (PAT)
-   [Step 2](02-orcid.html): Register for an ORCID iD
-   [Step 3](03-zotero.html): Sign-up for Zotero and setup Zotero reference management software
-   [Step 4](04-posit-cloud.html): Log into Posit Cloud with GitHub account and join workspace for the course
-   [Step 5](05-element.html): Log into Element and join the room for our course
-   [Step 6](06-survey.html): Fill out the pre-course survey by **Friday, 13th October**
-   Step 7: Read [@wilson2017]

## Thanks!

Thank you for working through these steps. You will hear from us again a day before the start of the course.
